## Linear Interpolation

In [2]:
time = [0, 20, 40, 60, 80, 100]
temp = [26.0, 48.6, 61.6, 71.2, 74.8, 75.2]

def linear_interpolation(x, x0, x1, y0, y1):
    return y0 + (y1 - y0) * (x - x0) / (x1 - x0)

celsius = linear_interpolation(50, 40, 60, 61.6, 71.2)
print(
    f"The temperature at 50 minutes is {celsius:.1f} degrees Celsius."
)

The temperature at 50 minutes is 66.4 degrees Celsius.


In [5]:
def do_interpolation(xp, x, y):
    for i, xi in enumerate(x):
        if xp < xi:
            return linear_interpolation(xp, x[i - 1], xi, y[i - 1], y[i])
    else:
        print("Given x-value out of range")
do_interpolation(50, time, temp)

66.4

## Lagrange's Interpolation Method

In [18]:
x = [0, 20, 40, 60, 80, 100]
y = [26.0, 48.6, 61.6, 71.2, 74.8, 75.2]
m = len(x)
value = 50.0
yp = 0
for i in range(m):
    p = 1
    for j in range(m):
        if i != j:
            p *= (value - x[j]) / (x[i] - x[j])
    yp += p * y[i]
print(f"The temperature at {value} minutes is {yp:.1f} degrees Celsius.")

The temperature at 50.0 minutes is 66.9 degrees Celsius.


## Newton's Interpolation Method

In [41]:
import numpy as np
x = [0.0, 1.5, 2.8, 4.4, 6.1, 8.0]
y = [0.0, 0.9, 2.5, 6.6, 7.7, 8.0]
n = len(x) - 1
Dy = np.zeros((n + 1, n + 1))
Dy[:, 0] = y
for j in range(n):
    for i in range(j+1, n+1):
        Dy[i, j+1] = (Dy[i, j] - Dy[j, j]) / (x[i] - x[j])
print(Dy)

[[ 0.          0.          0.          0.          0.          0.        ]
 [ 0.9         0.6         0.          0.          0.          0.        ]
 [ 2.5         0.89285714  0.22527473  0.          0.          0.        ]
 [ 6.6         1.5         0.31034483  0.05316881  0.          0.        ]
 [ 7.7         1.26229508  0.14397719 -0.02463562 -0.04576731  0.        ]
 [ 8.          1.          0.06153846 -0.03148774 -0.02351571  0.01171137]]


In [51]:
value = 4.4
yp = Dy[0, 0]
for i in range(n+1):
    p = 1
    for j in range(i):
        p *= (value - x[j])
    yp += p * Dy[i, i]
print(f"The value of the polynomial at {value} is {yp:.4f}.")

The value of the polynomial at 4.4 is 6.6000.


## Linear Regression

**Curve Fitting**

Curve fitting consiste en encontrar la ecuación de la curva que pasa a través de los data points dados con la menor desviación posible desde los puntos.

Así, la principal diferencia entre la Interpolación y el Ajuste de Curvas es que este último no tiene que coincidir con todos los data points dados.

La técnica usada para encontrar la ecuación de la curva es conocida como el Método de Mínimos Cuadrados, donde los cuadrados de las diferencias entre los data points dados y la curva ajustada deben ser minimizados.

In [13]:
x = [3, 4, 5, 6, 7, 8]
y = [0, 7, 17, 26, 35, 45]
n = len(x) 
x_sum = y_sum = x2_sum = xy_sum = 0

for i in range(n):
    x_sum += x[i] 
    y_sum += y[i]
    x2_sum += x[i] ** 2
    xy_sum += x[i] * y[i]

x_hat = x_sum / n
y_hat = y_sum / n

a = (y_hat*x2_sum - x_hat*xy_sum) / (x2_sum - n*x_hat**2)
b = (xy_sum - x_hat*y_sum) / (x2_sum - n*x_hat**2)

print(f"The equation of the line is y = {a:.2f} + {b:.2f}x.")

The equation of the line is y = -28.30 + 9.09x.


In [20]:
import numpy as np
x = np.array([3, 4, 5, 6, 7, 8])
y = np.array([0, 7, 17, 26, 35, 45])
n = len(x)
a = (np.mean(y)*np.sum(x**2) - np.mean(x)*np.sum(x*y)) / (np.sum(x**2) - n*np.mean(x)**2)
b = (np.sum(x*y) - np.mean(x)*np.sum(y)) / (np.sum(x**2) - n*np.mean(x)**2)
print(f"The equation of the line is y = {a:.2f} + {b:.2f}x.")

The equation of the line is y = -28.30 + 9.09x.


## Polynomial Fit

In [47]:
import numpy as np
x = np.arange(6)
y = np.array([2, 8, 14, 28, 39, 62])
m = len(x)
n = 3

A = np.zeros((n+1, n+1))
B = np.zeros(n+1)

for row in range(n+1):
    for col in range(n+1):
        if row == 0 and col == 0:
            A[row, col] = m
        else:
            A[row, col] = np.sum(x**(row+col))
    B[row] = np.sum(y*x**row)
print(A)

a = np.linalg.solve(A, B)
print(f"The equation of the line is y = {a[0]:.2f} + {a[1]:.2f}x + {a[2]:.2f}x^2 + {a[3]:.2f}x^3.")

[[6.0000e+00 1.5000e+01 5.5000e+01 2.2500e+02]
 [1.5000e+01 5.5000e+01 2.2500e+02 9.7900e+02]
 [5.5000e+01 2.2500e+02 9.7900e+02 4.4250e+03]
 [2.2500e+02 9.7900e+02 4.4250e+03 2.0515e+04]]
The equation of the line is y = 1.93 + 5.68x + -0.00x^2 + 0.25x^3.


## Interpolation and Curve Fitting Functions in SciPy

In [53]:
import scipy as sp
x = [0, 20, 40, 60, 80, 100]
y = [26.0, 48.6, 61.6, 71.2, 74.8, 75.2]

**Lineal**

In [60]:
f = sp.interpolate.interp1d(x, y)
f(40)

array(61.6)

In [61]:
f = sp.interpolate.interp1d(x, y, kind='quadratic')
f(50)

array(66.95208333)

**Lagrange**

In [63]:
L = sp.interpolate.lagrange(x, y)
L

poly1d([ 3.69791667e-08, -9.68750000e-06,  9.21875000e-04, -4.46250000e-02,
        1.72533333e+00,  2.60000000e+01])

In [64]:
L(40)

61.599999999999746

In [65]:
L(50)

66.94765624999957

**Linear Regression**

In [66]:
import scipy as sp
x = np.array([3, 4, 5, 6, 7, 8])
y = np.array([0, 7, 17, 26, 35, 45])

In [67]:
L = sp.stats.linregress(x, y)
L

LinregressResult(slope=9.085714285714285, intercept=-28.3047619047619, rvalue=0.9990651680982869, pvalue=1.3104575468971522e-06, stderr=0.19656921371950828, intercept_stderr=1.1320520969077084)

In [68]:
L.slope

9.085714285714285

In [69]:
print(f"The equation of the line is y = {L.intercept:.2f} + {L.slope:.2f}x.")

The equation of the line is y = -28.30 + 9.09x.


**Curve Fit**

In [70]:
x = np.arange(6)
y = np.array([2, 8, 14, 28, 39, 62])

In [73]:
def f(x, a0, a1, a2, a3):
    return a0 + a1*x + a2*x**2 + a3*x**3
a, b = sp.optimize.curve_fit(f, x, y)
print(f"The equation of the line is y = {a[0]:.2f} + {a[1]:.2f}x + {a[2]:.2f}x^2 + {a[3]:.2f}x^3.")

The equation of the line is y = 1.93 + 5.68x + -0.00x^2 + 0.25x^3.
